### ISSUE TITLE
Error prepareFilename() is not defined

### ISSUE THREAD

**Issue by scagle** [TeamMsgExtractor/msg-extractor#189]
**Bug Metadata**
* Version of extract_msg: [v0.28.4 (master)]
* Your python version: Python [3.9]
* How did you launch extract_msg?
  - [X] I used the extract_msg package

**Describe the bug**
Looks like the newest version (https://github.com/TeamMsgExtractor/msg-extractor/commit/389b281c3cfbe7b076e4c282cd40cb8353b9704f) introduced a small bug in `attachments.py` when loading .msg files with attachments. I ran using the pip package, on MacOS with python3.9. It appears to be resolvable by appending `prepareFilename` in the import list of `attachment.py`.

**Fix**
line 10 of attachment.py:
```
from extract_msg.utils import openMsg, inputToString, verifyPropertyId, verifyType, prepareFilename
```

**What code did you use or can we use to reproduce this error?**
v0.28.4 (master)

**Traceback**
( [...] = my edits )
```
Error with file '[...].msg': Traceback (most recent call last):
  File "[...]/Library/Python/3.9/lib/python/site-packages/extract_msg/__main__.py", line 51, in main
    msg.save(toJson = args.json, useFileName = args.use_filename, ContentId = args.cid)#, html = args.html, rtf = args.html, args.allowFallback)
  File "[...]/Library/Python/3.9/lib/python/site-packages/extract_msg/message.py", line 126, in save
    attachmentNames.append(attachment.save(ContentId, toJson, useFileName, raw))#, html = html, rtf = rtf, allowFallback = allowFallback))
  File "[...]/Library/Python/3.9/lib/python/site-packages/extract_msg/attachment.py", line 80, in save
    filename = prepareFilename(inputToString(filename, self.msg.stringEncoding))
NameError: name 'prepareFilename' is not defined
```

**Comment by TheElementalOfDestruction** [comment]
Aw shoot. Of course I forgot to use a file with an attachment during my testing. I'll get a fix out quickly.

**Comment by TheElementalOfDestruction** [comment]
This should be fixed in 0.28.5. I managed to save an attachment without issue. Let me know if you continue to have problems.

**Comment by scagle** [comment]
Looks like that worked on my machine! Thank you!

**Comment by Yoyoma22** [comment]
Did not for me, but the fix is easy.  I pulled the code and I will make a test for attachments.  We should always run the test cases prior to commit, as they would have found the issue.

**Comment by TheElementalOfDestruction** [comment]
@Yoyoma22 I tested it myself and it worked fine. Are you on the correct version (0.28.5)? And if so, what was the traceback?

**Comment by Yoyoma22** [comment]
Just confirmed it is at 0.28.5, had a pipenv update issue but it is fixed now.  Thanks!
