### ISSUE TITLE
Unable to read a message store in ADLS from Synapse Spark Notebook

### ISSUE THREAD

**Issue by Prasantkp** [TeamMsgExtractor/msg-extractor#247]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [0.30.8]
* Your python version: Python [3.8]
* How did you launch extract_msg?
  - [Yes ] I used the extract_msg package

**Describe the bug**
An msg file Confidential_Info_With_Attachments.msg is stored in Azure ADLS location. I am trying to leverage extract_msg to read this message from Synapse  Spark Notebook (Spark Version - 3.1). While accessing the message its causing "FileNotFoundError: [Errno 2] No such file or directory: ". I tried directly using the ADLS path and also by creating mount point using linked service . It caused the same exception.

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
msg = extract_msg.Message("/mntadls1/Confidential_Info_With_Attachments.msg")
msg = extract_msg.Message("abfss://container-dev@storageaccount.dfs.core.windows.net/scan-redact/Source/Confidential_Info_With_Attachments.msg")
```

Is there a message.msg file you want to share to help us reproduce this?
No. Its happening for any message.
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
Errno 2] No such file or directory: '/mntadls1/Confidential_Info_With_Attachments.msg'FileNotFoundError: [Errno 2] No such file or directory: '/mntadls1/Confidential_Info_With_Attachments.msg'
Traceback (most recent call last):

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/extract_msg/message_base.py", line 54, in __init__
    super().__init__(path, prefix, attachmentClass, filename, overrideEncoding, attachmentErrorBehavior)

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/extract_msg/msg.py", line 55, in __init__
    super().__init__(path)

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/olefile/olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/olefile/olefile.py", line 1169, in open
    self.fp = open(filename, mode)

FileNotFoundError: [Errno 2] No such file or directory: '/mntadls1/Confidential_Info_With_Attachments.msg'
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfDestruction** [comment]
If you try and use the python default `open` function, does that succeed?

**Comment by TheElementalOfDestruction** [comment]
Never mind, reading the traceback shows that the python default open is used by olefile. 

This is not a bug with the module, it's one of the following:
1. Python has no support for accesing a file from ADLS
2. A bug in python is preventing it from finding that file
3. The paths you have given are just generally invalid to the computer's filesystem

**Comment by Prasantkp** [comment]
We are able to access the ADLS files using MSSparkUtils library. This message is not stored on the Computer file system. Its on Storage Account in Azure. Is there any example of reading a message from Azure Storage Account.

**Comment by TheElementalOfDestruction** [comment]
Extract msg supports exactly 3 ways of working with a file:
1. Provide it with a python recognizable path (a path that the default `open` function supports).
2. The bytes that make up the file (a `bytes` instance in python).
3. A file like object.

If you can give extract_msg any of those it should be able to open. Once open then it may be something to do with the module itself and I can help you further.

**Comment by Prasantkp** [comment]
> Extract msg supports exactly 3 ways of working with a file:
> 
> 1. Provide it with a python recognizable path (a path that the default `open` function supports).
> 2. The bytes that make up the file (a `bytes` instance in python).
> 3. A file like object.
> 
> If you can give extract_msg any of those it should be able to open. Once open then it may be something to do with the module itself and I can help you further.

Let me try out these and come back. Thank You.

**Comment by Prasantkp** [comment]
> > Extract msg supports exactly 3 ways of working with a file:
> > 
> > 1. Provide it with a python recognizable path (a path that the default `open` function supports).
> > 2. The bytes that make up the file (a `bytes` instance in python).
> > 3. A file like object.
> > 
> > If you can give extract_msg any of those it should be able to open. Once open then it may be something to do with the module itself and I can help you further.
> 
> Let me try out these and come back. Thank You.
The bytes that make up the file (a bytes instance in python) - We were able to make it work with this approach. Thank You :-)

**Comment by TheElementalOfDestruction** [comment]
To help clarify the solution to such an issue in the future, I have added a small paragraph into https://github.com/TeamMsgExtractor/msg-extractor/wiki/Using-msg-extractor-In-Your-Own-Code
