### ISSUE TITLE
Import bug for older Python versions

### ISSUE THREAD

**Issue by gwiedeman** [TeamMsgExtractor/msg-extractor#280]
**Bug Metadata**
* Version of extract_msg: >0.35.0
* Your python version: Python 3.7.13 and 3.8.13 (3.9.13 is good)
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
Looks like there's a weird import bug or incompatibility introduced in `0.35.0` for only older python versions 3.7 and 3.8. `0.34.3` is fine.

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
import extract_msg
```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\Scripts\mailbagit-script.py", line 33, in <module>
    sys.exit(load_entry_point('mailbagit', 'console_scripts', 'mailbagit')())
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\Scripts\mailbagit-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\importlib_metadata\__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "c:\users\greg\appdata\local\programs\python\python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "f:\projects\mailbagit\mailbagit\__init__.py", line 39, in <module>
    import_formats(plugin_dirs["formats"])
  File "f:\projects\mailbagit\mailbagit\email_account.py", line 65, in import_formats
    import mailbagit.formats.msg
  File "f:\projects\mailbagit\mailbagit\formats\msg.py", line 1, in <module>
    import extract_msg
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\__init__.py", line 36, in <module>
    from .appointment import AppointmentMeeting
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\appointment.py", line 5, in <module>
    from .calendar import Calendar
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\calendar.py", line 6, in <module>
    from .calendar_base import CalendarBase
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\calendar_base.py", line 8, in <module>
    from .message_base import MessageBase
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\message_base.py", line 41, in <module>
    class MessageBase(MSGFile):
  File "C:\Users\Greg\.virtualenvs\Projects-qq1G4vLi\lib\site-packages\extract_msg\message_base.py", line 210, in MessageBase
    def getInjectableHeader(self, prefix : str, joinStr : str, suffix : str, formatter : Callable[str, str]) -> str:
  File "c:\users\greg\appdata\local\programs\python\python37-32\lib\typing.py", line 752, in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
TypeError: Callable[args, result]: args must be a list. Got <class 'str'>
```

**Comment by TheElementalOfDestruction** [comment]
Nope, that's actually me just not knowing the syntax for Callable and being called out on it, lmao. Didn't realize it was a list of type followed by the return type. Let me fix that up real quick

**Comment by TheElementalOfDestruction** [comment]
There we go, fixed it. I actually still have a 3.6 install of python so I checked back to there to be sure there weren't others.

**Comment by gwiedeman** [comment]
Thanks for the quick fix!
