### ISSUE TITLE
VisitError: Error trying to process rule "RTFESCAPE": 'cp949' codec can't decode byte 0xd8 in position 0: incomplete multibyte sequence

### ISSUE THREAD

**Issue by hyunsikhwang** [TeamMsgExtractor/msg-extractor#319]
* Version of extract_msg: [0.38.4]
* Python version: Python [3.9.13]
* How did you launch extract_msg?
  - [x] My command line or
  - [ ] I used the extract_msg package

**Describe the bug**
No error occurs when I tried to extract only plain text, but with HTML option, an error occurs with the message below.

Error with file "message.msg": Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 1150, in htmlBody
    return self._htmlBody
AttributeError: 'Message' object has no attribute '_htmlBody'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 989, in deencapsulatedRtf
    return self._deencapsultor
AttributeError: 'Message' object has no attribute '_deencapsultor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\lark\visitors.py", line 106, in _call_userfunc_token
    return f(token)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\RTFDE\transformers.py", line 189, in RTFESCAPE
    decoded = hex_bytes.decode(self.rtf_codec)
UnicodeDecodeError: 'cp949' codec can't decode byte 0xd8 in position 0: incomplete multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\__main__.py", line 116, in main
    msg.save(**kwargs)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 833, in save
    if self.htmlBody:
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 1157, in htmlBody
    self._htmlBody = self.deencapsulateBody(self.rtfBody, DeencapType.HTML)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 190, in deencapsulateBody
    if self.deencapsulatedRtf and self.deencapsulatedRtf.content_type == 'html':
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\extract_msg\message_base.py", line 1025, in deencapsulatedRtf
    self._deencapsultor.deencapsulate()
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\RTFDE\deencapsulate.py", line 134, in deencapsulate
    self.content = self._deencapsulate_from_tree()
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\RTFDE\deencapsulate.py", line 186, in _deencapsulate_from_tree
    cleaned_text = cleaner.transform(stripped_tree)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\lark\visitors.py", line 130, in transform
    return self._transform_tree(tree)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\lark\visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\lark\visitors.py", line 118, in _transform_children
    yield self._call_userfunc_token(c)
  File "C:\Users\xxxxxxxx\Anaconda3\lib\site-packages\lark\visitors.py", line 110, in _call_userfunc_token
    raise VisitError(token.type, token, e)
lark.exceptions.VisitError: Error trying to process rule "RTFESCAPE":

'cp949' codec can't decode byte 0xd8 in position 0: incomplete multibyte sequence

```
[put your code here]
python -m extract_msg "message.msg" --html

Is there a message.msg file you want to share to help us reproduce this?
Unfortunately, I cannot share the msg file because some confidential contents must not be sent outside.

**Comment by TheElementalOfDestruction** [comment]
This is an issue with RTFDE specifically, not with extract-msg. Furthermore, it seems to most likely be *directly* related to the data inside the body (looks to contain some kind of escaped character either starting with `\u` or `\'` followed by a few hex characters). 

If I'm understanding the error from that correctly, what it *instead* got was a completely invalid character (0xD8, which in iso-8859-1 is the `Ø` character). Of course, since that isn't my code, I can only really guess without going piece by piece through the other library.

You should probably open the issue here on their GitHub, though without the body data I don't know if there is much they can do.

If I could have some kind of access to the data, I could probably tell you more. I might be able to write some code to extract the relevent parts of the data without compromising any of the confidential data if you would be interested in that, as it could help in finding the problem. Of course, I would also recommend you check any data you would be sending to me to double check none of it is sensitive at all. If you want to do that, we can try to do it here, in this issue, or you can contact me through the discord listed in the readme.
