### ISSUE TITLE
[BUG] Some files don't export correctly due to AttributeError

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [TeamMsgExtractor/msg-extractor#326]
Extract-msg version 0.38.4 has a bug that causes some files to fail to export if the top of the red-black tree happens to end up as a storage instead of a stream. This is because the top of the tree is the only part that doesn't actually check the type of the node.

This will be fixed by ensuring all nodes are `_DirectoryEntry`s instead of mixing `dict`s into it for no reason. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\extract_msg\msg.py", line 515, in export
    writer.write(path)
  File "C:\Program Files\Python39\lib\site-packages\extract_msg\ole_writer.py", line 765, in write
    entries = self._writeDirectoryEntries(f, offset)
  File "C:\Program Files\Python39\lib\site-packages\extract_msg\ole_writer.py", line 465, in _writeDirectoryEntries
    entries = self._treeSort(startingSector)
  File "C:\Program Files\Python39\lib\site-packages\extract_msg\ole_writer.py", line 310, in _treeSort
    entry.childID = entry.childTreeRoot.id if entry.childTreeRoot else 0xFFFFFFFF
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by TheElementalOfDestruction** [comment]
Fixed in 0.39.0
